name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

env:
  NODE_JS: 16

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          [
            predefined-prod,
            predefined-test,
            native-wss-prod,
            native-wss-test,
            waku-connect,
          ]
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_JS }}
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - name: Run ${{ matrix.test }}
        run: npm run ${{ matrix.test }}

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_JS }}
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: npm run test:lint
      - run: npm run test:prettier
